### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by SzotsGabor** [cosmobobak/virtue#3]
Hi Cosmo,

May I suggest to include the version number in the file name? It may lead to accidents when all are called virtue.

Gabor Szots
CCRL testing group

**Comment by cosmobobak** [comment]
I will do that! additionally, I'm probably going to remove the Linux binaries, because they have proven highly nonportable, and will instead recommend building from source on Linux.

**Comment by cosmobobak** [comment]
okay, that's done. binaries will be in the format `viridithasX.X.X.exe` going forward.
