### ISSUE TITLE
2.4.0 says it is 2.3.0

### ISSUE THREAD

**Issue by SzotsGabor** [cosmobobak/virtue#4]
No other comment

**Comment by cosmobobak** [comment]
ah! my carelessness - will fix later today

**Comment by cosmobobak** [comment]
binary attached to the 2.4 release is correct now, will unfortunately still report incorrect version if build from source

**Comment by SzotsGabor** [comment]
It does not seem so.

**Comment by cosmobobak** [comment]
you were right, i was getting confused between the cargo version and the string written in main.rs. I've reworked viri such that these can't get out-of-sync again. Sorry for screwing things up! binary in release 2.4 *definitely* works now

**Comment by SzotsGabor** [comment]
Upon starting the engine indeed displays id name Viridithas 2.4.0.

However, after typing uci the response is id name Viridithas.

But I'm picky by nature.

**Comment by cosmobobak** [comment]
oh christ, i just can't get this right, can i? should be fixed now.
